###
POST http://localhost:8080/rule/add
Content-Type: application/json

{
  "resource": "GET:/shangban",
  "controlBehavior": 0,
  "count": 0,
  "grade": 1,
  "appId": "yuhao",
  "strategy": 0
}

###
GET http://localhost:8080/hello

###
POST http://localhost:8080/test
Content-Type: application/json

{
  "method": "A"
}