###
POST http://localhost:8080/rule/add
Content-Type: application/json

{
  "resource": "GET:/block",
  "controlBehavior": 0,
  "count": 0,
  "grade": 1,
  "limitApp": "default",
  "strategy": 0
}

###
GET http://localhost:8080/block