---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuhaochen.
--- DateTime: 2022/5/20 14:38
---


function random_seed()
    local in_file = io.open("/dev/urandom", "r")
    if in_file ~= nil then
        local d = in_file:read(4)
        math.randomseed(os.time() + d:byte(1) + (d:byte(2) * 256) + (d:byte(3) * 65536) + (d:byte(4) * 4294967296))
    else
        math.randomseed(tostring(os.time()):reverse():sub(1, 7))
    end
end

request = function()
    random_seed()
    wrk.method = "GET"
    wrk.path = "/async/echo/" .. tostring(math.random(0, 5))
    wrk.headers["Content-Type"] = "application/json"
    wrk.headers["appId"] = tostring(math.random(0, 5))
    return wrk.format()
end
