###
POST http://localhost:8080/rule/add
Content-Type: application/json

{
  "resource": "GET:/hello",
  "controlBehavior": 0,
  "count": 0,
  "grade": 1,
  "appId": "yuhao",
  "strategy": 0
}

###
GET http://localhost:8080/hello